"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.customHeaders = exports.client = exports.cognitiveServicesCredentials = exports.kbid = exports.QNAMAKER_ENDPOINT = exports.QNAMAKER_KEY = void 0;
const ms_rest_azure_js_1 = require("@azure/ms-rest-azure-js");
const cognitiveservices_qnamaker_runtime_1 = require("@azure/cognitiveservices-qnamaker-runtime");
exports.QNAMAKER_KEY = process.env["QNAMAKER_KEY"] || "<QNAMAKER_KEY>";
exports.QNAMAKER_ENDPOINT = process.env["QNAMAKER_ENDPOINT"] || "<QNAMAKER_ENDPOINT>";
exports.kbid = process.env["QNAMAKER_KNOWLEDGE_BASE_ID"] || "<QNAMAKER_KNOWLEDGE_BASE_ID>";
exports.cognitiveServicesCredentials = new ms_rest_azure_js_1.CognitiveServicesCredentials(exports.QNAMAKER_KEY);
exports.client = new cognitiveservices_qnamaker_runtime_1.QnAMakerRuntimeClient(exports.cognitiveServicesCredentials, exports.QNAMAKER_ENDPOINT);
exports.customHeaders = { Authorization: `EndpointKey ${exports.QNAMAKER_KEY}` };
