version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: caspr-app
    depends_on:
      - postgres
    links: 
      - postgres
    volumes:
      - ./prisma:/usr/src/app/prisma
      - ./server:/usr/src/app/server
      - /usr/src/app/node_modules/
    restart: on-failure
    env_file: docker/app/.env
    command: [bash, -c, "prisma migrate deploy --preview-feature && cd server && yarn run start"]
  www:
    build:
      context: .
      dockerfile:  docker/www/Dockerfile
    volumes:
      - ./www:/usr/src/app/www
      - /usr/src/app/node_modules/
    ports:
      - "80:3000"
    links:
      - server
    depends_on:
      - server
    env_file: docker/app/.env
    command: [bash, -c, "cd www && yarn run start"]
  postgres:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: caspr-db
    ports:
      - "5432:5432"
    env_file: docker/db/.env
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5