FROM node:latest

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
#COPY package*.json ./
# Bundle app source
COPY . .
RUN npm install -g typescript
RUN npm install -g ts-node
RUN npm install -g @prisma/cli
RUN npm install
RUN prisma generate
RUN npm run build
#RUN prisma migrate deploy --preview-feature
# If you are building your code for production
# RUN npm ci --only=production



EXPOSE 3000
CMD [ "ts-node", "./server/index.ts" ]