# docker-compose.yml
version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: caspr-app
    depends_on:
      - postgres
    links: 
      - postgres
    volumes:
      - ./server:/usr/src/app/server
    restart: on-failure
    env_file: docker/app/.env
    command: [bash, -c, "cd ./server && prisma migrate deploy --preview-feature && yarn run start"]
  www:
    build:
      context: .
      dockerfile:  docker/app/Dockerfile
    command: [bash, -c, "cd ./www && yarn run start"]
    volumes:
       - ./www/src:/usr/src/app/www/src
       - ./www/public:/usr/src/app/www/public
    ports:
      - "80:3000"
    links:
      - server
    depends_on:
      - server
  postgres:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    image: caspr-db
    ports:
      - "5432:5432"
    env_file: docker/db/.env
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5