# docker-compose.yml
version: "3.3"
services:
  app:
    image: codefly.azurecr.io/caspr:latest
    #build: .
    depends_on:
      - postgres
    ports:
      - "80:3000"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db