# docker-compose.yml
version: "3.3"
services:
  server:
    build:
      context: ../.
      dockerfile: docker/app/Dockerfile
    image: caspr-app
    depends_on:
      - postgres
    links: 
      - postgres
    volumes:
      - ../server:/usr/src/app/server
    restart: on-failure
    env_file: app/.env
    command: [bash, -c, "prisma migrate deploy --preview-feature && npm run start:server"]
  www:
    build:
      context: ../.
      dockerfile:  docker/app/Dockerfile
    command: "npm run start:www"
    volumes:
      - ../www/src:/usr/src/app/www/src
      - ../www/public:/usr/src/app/www/public
    ports:
      - "80:3000"
    links:
      - server
    depends_on:
      - server
  postgres:
    build:
      context: ../.
      dockerfile: docker/db/Dockerfile
    image: caspr-db
    env_file: db/.env
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5